CREATE TABLE Videogame ( 
VID CHAR(50),
Genre CHAR(50),
Name CHAR(50),
SRBRating CHAR(5), 
PRIMARY KEY (VID));

CREATE TABLE Company ( 
CID CHAR(50),
Name CHAR(50),
FoundedDate INT,
PRIMARY KEY (CID));

CREATE TABLE Rating ( 
VID CHAR(50),
CID CHAR(50),
AverageRating Float,
PRIMARY KEY(VID,CID),
FOREIGN KEY(VID)
REFERENCES Videogame ON DELETE CASCADE,
FOREIGN KEY(CID)
REFERENCES Company ON DELETE CASCADE);

CREATE TABLE Crew ( 
CRID CHAR(50),
Salary INT,
Role CHAR(50),
PRIMARY KEY (CRID));

CREATE TABLE VideoGameProducer ( 
CID CHAR(50),
PRIMARY KEY(CID),
FOREIGN KEY (CID)
REFERENCES Company ON DELETE CASCADE);

CREATE TABLE Person (
ID CHAR(50),
Date_of_Birth DATE,
Name CHAR(50),
PRIMARY KEY(ID));

CREATE TABLE Creators ( 
VID CHAR(50),
CRID CHAR(50),
PRIMARY KEY (VID, CRID),
FOREIGN KEY (CRID)
REFERENCES Crew ON DELETE CASCADE,
FOREIGN KEY (VID)
REFERENCES Videogame ON DELETE CASCADE);

CREATE TABLE Member ( 
ID CHAR(50),
CRID CHAR(50),
PRIMARY KEY (CRID,ID),
FOREIGN KEY (CRID)
REFERENCES Crew ON DELETE CASCADE,
FOREIGN KEY (ID)
REFERENCES Person ON DELETE CASCADE);

CREATE TABLE Backer ( 
VID CHAR(50),
CID CHAR(50),
PRIMARY KEY (CID,VID),
FOREIGN KEY (CID)
REFERENCES Company ON DELETE CASCADE,
FOREIGN KEY (VID)
REFERENCES Videogame ON DELETE CASCADE);

CREATE TABLE Score ( 
CID CHAR(50),
VID CHAR(50),
PRIMARY KEY (CID,VID),
FOREIGN KEY (CID)
REFERENCES Company ON DELETE CASCADE,
FOREIGN KEY (VID)
REFERENCES Videogame ON DELETE CASCADE);

CREATE TABLE PresentedScore( 
CID CHAR(50) NOT NULL,
AvgRating  Float,
PRIMARY KEY (AvgRating),
FOREIGN KEY (CID)
REFERENCES Company ON DELETE CASCADE
);

CREATE TABLE Organization ( 
CID CHAR(50),
PRIMARY KEY(CID),
FOREIGN KEY (CID)
REFERENCES Company ON DELETE CASCADE);

CREATE TABLE Critic ( 
CID CHAR(50),
PRIMARY KEY(CID),
FOREIGN KEY (CID)
REFERENCES Company ON DELETE CASCADE);

CREATE TABLE Given ( 
VID CHAR(20),
CID CHAR(20),
PRIMARY KEY (CID,VID),
FOREIGN KEY (CID)
REFERENCES Company ON DELETE CASCADE,
FOREIGN KEY (VID)
REFERENCES Videogame ON DELETE CASCADE);

CREATE TABLE AwardPresented (
Year INT,
Name CHAR(50),
CID Char(20) NOT NULL,
PRIMARY KEY(Year, Name),
FOREIGN KEY(CID)
REFERENCES Company ON DELETE CASCADE);

